version: '3.5'
services:
  sv_nginx:
    container_name: sv_nginx
    volumes:
      - ./../backend:/var/www/backend
      - ./../frontend:/var/www/frontend
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - socket:/run/php-fpm
    image: nginx
    ports:
      - "80:80"
    links:
      - sv_fpm
      - sv_node
  sv_node:
    container_name: sv_node
    volumes:
      - ./../frontend:/var/www/frontend
    working_dir: /var/www/frontend
    command: npm run serve
    build:
      context: ./node
      args:
        - UID
        - USER_NAME
    user: ${USER_NAME}
    ports:
      - "8080:8080"
  sv_fpm:
    container_name: sv_fpm
    build:
      context: ./fpm
      args:
        - UID
        - USER_NAME
    user: ${USER_NAME}
    working_dir: /var/www/backend
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./../backend:/var/www/backend
      - ./fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./fpm/php.ini:/usr/local/etc/php/php.ini
      - /home/${USER_NAME}/.ssh:/home/${USER_NAME}/.ssh
      - socket:/run/php-fpm
    extra_hosts:
      - host.docker.internal:host-gateway
  sv_mysql:
    container_name: sv_mysql
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=user_name
      - MYSQL_PASSWORD=user_password
    volumes:
      - ./mysql/dump:/docker-entrypoint-initdb.d
      - ./mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    ports:
      - 3306:3306
  sv_mailhog:
    container_name: sv_mailhog
    image: mailhog/mailhog
    ports:
      - 8025:8025
volumes:
  socket:
